import jsPDF from "jspdf";
import type { TranslationResult } from "@/pages/Index";

export function generateResumePDF(result: TranslationResult, fullName: string) {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });

  // Load Heebo font via standard font (jsPDF doesn't support Hebrew natively well,
  // so we'll use a workaround with the standard font for structure and embed text as-is)
  // For proper Hebrew we need to add the font. We'll use the built-in approach.

  const pageWidth = 210;
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;
  let y = 20;

  // Header bar
  doc.setFillColor(37, 99, 235); // primary blue
  doc.rect(0, 0, pageWidth, 40, "F");

  // Name (white text on blue)
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.setFont("Helvetica", "bold");
  const nameLines = doc.splitTextToSize(fullName, contentWidth);
  nameLines.forEach((line: string) => {
    doc.text(line, pageWidth - margin, y + 4, { align: "right" });
    y += 10;
  });

  // Title
  doc.setFontSize(13);
  doc.setFont("Helvetica", "normal");
  doc.text(result.title, pageWidth - margin, y + 4, { align: "right" });
  y = 50;

  doc.setTextColor(30, 41, 59); // dark foreground

  // Summary section
  doc.setFontSize(14);
  doc.setFont("Helvetica", "bold");
  doc.setTextColor(37, 99, 235);
  doc.text("Professional Summary", pageWidth - margin, y, { align: "right" });
  y += 2;
  doc.setDrawColor(37, 99, 235);
  doc.setLineWidth(0.5);
  doc.line(margin, y, pageWidth - margin, y);
  y += 7;

  doc.setFontSize(10);
  doc.setFont("Helvetica", "normal");
  doc.setTextColor(51, 65, 85);
  const summaryLines = doc.splitTextToSize(result.summary, contentWidth);
  summaryLines.forEach((line: string) => {
    doc.text(line, pageWidth - margin, y, { align: "right" });
    y += 5;
  });
  y += 5;

  // Skills section
  doc.setFontSize(14);
  doc.setFont("Helvetica", "bold");
  doc.setTextColor(37, 99, 235);
  doc.text("Key Skills", pageWidth - margin, y, { align: "right" });
  y += 2;
  doc.line(margin, y, pageWidth - margin, y);
  y += 7;

  doc.setFontSize(10);
  doc.setFont("Helvetica", "normal");
  doc.setTextColor(51, 65, 85);

  // Skills in a grid-like layout
  const skillCols = 2;
  const colWidth = contentWidth / skillCols;
  result.skills.forEach((skill, i) => {
    const col = i % skillCols;
    const x = pageWidth - margin - col * colWidth;
    doc.text(`• ${skill}`, x, y, { align: "right" });
    if (col === skillCols - 1 || i === result.skills.length - 1) {
      y += 6;
    }
  });
  y += 3;

  // Experience section
  doc.setFontSize(14);
  doc.setFont("Helvetica", "bold");
  doc.setTextColor(37, 99, 235);
  doc.text("Professional Experience", pageWidth - margin, y, { align: "right" });
  y += 2;
  doc.line(margin, y, pageWidth - margin, y);
  y += 7;

  doc.setFontSize(10);
  doc.setFont("Helvetica", "normal");
  doc.setTextColor(51, 65, 85);
  result.experience.forEach((item) => {
    const lines = doc.splitTextToSize(`• ${item}`, contentWidth - 5);
    lines.forEach((line: string) => {
      if (y > 275) return; // prevent overflow
      doc.text(line, pageWidth - margin, y, { align: "right" });
      y += 5;
    });
    y += 2;
  });

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(148, 163, 184);
  doc.text("Generated by Skill-Bridge", pageWidth / 2, 290, { align: "center" });

  doc.save(`${fullName.replace(/\s+/g, "_")}_Resume.pdf`);
}
