import { Dialog, DialogContent, DialogTitle } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { FileDown } from "lucide-react";
import { generateResumePDF } from "@/lib/generatePdf";
import type { TranslationResult } from "@/pages/Index";

interface ResumePreviewModalProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  result: TranslationResult;
  fullName: string;
}

const ResumePreviewModal = ({ open, onOpenChange, result, fullName }: ResumePreviewModalProps) => {
  const handleDownload = async () => {
    await generateResumePDF(result, fullName);
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-4xl h-[90vh] p-0 bg-[#3a3a3a] border-none overflow-hidden flex flex-col">
        <DialogTitle className="sr-only">תצוגה מקדימה של קורות חיים</DialogTitle>

        {/* Resume A4 page */}
        <div className="flex-1 overflow-auto p-6 md:p-10 flex justify-center">
          <div
            className="bg-white shadow-2xl w-full max-w-[794px] rounded-sm"
            style={{ fontFamily: "'Heebo', sans-serif", direction: "rtl", color: "#1e293b" }}
          >
            {/* Header */}
            <div style={{ background: "#2563eb", padding: "28px 36px", borderRadius: "4px 4px 0 0" }}>
              <h1 style={{ color: "white", fontSize: "28px", fontWeight: 800, margin: "0 0 6px 0" }}>{fullName}</h1>
              <p style={{ color: "rgba(255,255,255,0.85)", fontSize: "16px", margin: 0 }}>{result.title}</p>
            </div>

            <div style={{ padding: "28px 36px" }}>
              {/* Summary */}
              <div style={{ marginBottom: "20px" }}>
                <h2 style={{ color: "#2563eb", fontSize: "17px", fontWeight: 700, borderBottom: "2px solid #2563eb", paddingBottom: "6px", margin: "0 0 10px 0" }}>תקציר מקצועי</h2>
                <p style={{ fontSize: "13px", lineHeight: 1.7, margin: 0, color: "#334155" }}>{result.summary}</p>
              </div>

              {/* Skills */}
              <div style={{ marginBottom: "20px" }}>
                <h2 style={{ color: "#2563eb", fontSize: "17px", fontWeight: 700, borderBottom: "2px solid #2563eb", paddingBottom: "6px", margin: "0 0 10px 0" }}>כישורים מקצועיים</h2>
                <div style={{ display: "flex", flexWrap: "wrap", gap: "8px" }}>
                  {result.skills.map((s, i) => (
                    <span key={i} style={{ background: "#eff6ff", color: "#1e40af", padding: "4px 14px", borderRadius: "20px", fontSize: "12px", fontWeight: 500 }}>{s}</span>
                  ))}
                </div>
              </div>

              {/* Experience */}
              <div style={{ marginBottom: "20px" }}>
                <h2 style={{ color: "#2563eb", fontSize: "17px", fontWeight: 700, borderBottom: "2px solid #2563eb", paddingBottom: "6px", margin: "0 0 10px 0" }}>ניסיון מקצועי</h2>
                <ul style={{ listStyle: "none", padding: 0, margin: 0 }}>
                  {result.experience.map((item, i) => (
                    <li key={i} style={{ fontSize: "13px", lineHeight: 1.7, marginBottom: "6px", paddingRight: "16px", position: "relative", color: "#334155" }}>
                      <span style={{ position: "absolute", right: 0, top: "8px", width: "6px", height: "6px", background: "#2563eb", borderRadius: "50%" }} />
                      {item}
                    </li>
                  ))}
                </ul>
              </div>

              <p style={{ textAlign: "center", fontSize: "10px", color: "#94a3b8", marginTop: "32px" }}>Generated by Skill-Bridge</p>
            </div>
          </div>
        </div>

        {/* Download bar */}
        <div className="p-4 bg-[#2d2d2d] flex justify-center">
          <Button onClick={handleDownload} size="lg" className="gap-2">
            <FileDown className="h-5 w-5" />
            הורד PDF
          </Button>
        </div>
      </DialogContent>
    </Dialog>
  );
};

export default ResumePreviewModal;
